#!/usr/bin/env python3

# Copyright (C) 2006, Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import os
import sys
import re

source = os.path.abspath(sys.argv[1])

f = open(source, 'r')
data = f.read()
f.close()

stroke = None
fill = None

match = re.search('stroke=\"\#(\w+)\"', data)
if match:
    stroke = match.group(1)

for match in re.findall('[fill|stroke]=\"\#(\w+)\"', data):
    if match != stroke:
        fill = match

if fill:
    data = re.sub('\#' + fill, '&fill_color;', data)
if stroke:
    data = re.sub('\#' + stroke, '&stroke_color;', data)

entities = ''
if stroke:
    entities += '\t<!ENTITY stroke_color "#' + stroke + '">\n'
if fill:
    entities += '\t<!ENTITY fill_color "#' + fill + '">\n'
entities += ']>'

data = re.sub('\]\>', entities, data)

f = open(source, 'w')
f.write(data)
f.close()
