#!/usr/bin/env python

# Copyright (C) 2006, Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import os
import sys
import re

source = os.path.abspath(sys.argv[1])

f = open(source, 'r')
data = f.read()
f.close()

match = re.search('stroke=\"\#(\w+)\"', data)
stroke = match.group(1)

for match in re.findall('[fill|stroke]=\"\#(\w+)\"', data):
    if match != stroke:
        fill = match

entities = '\t<!ENTITY fill_color "#FFFFFF">\n' \
           '\t<!ENTITY stroke_color "#000000">\n]>'
data = re.sub('\]\>', entities, data)

data = re.sub('\#' + fill, '&fill_color;', data)
data = re.sub('\#' + stroke, '&stroke_color;', data)

print data
